'''
This class uses objects of the class 'Slot' to build schedules that can be processed by the constraint handling classes
and placed into the tree structure generated by the Tree class. Every object in the schedule must be of the class 'Slot'.

'''

from ScheduleObjects.ActivitySlot import Slot
from ScheduleObjects.Game import Game
from ScheduleObjects.Practice import Practice

class Schedule:
    # Empty constructor (TODO)
    def __init__(self) -> None:
        self.mwfg = [set() for i in range(13)]
        self.trg = [set() for i in range(7)]
        self.mwp = [set() for i in range(13)]
        self.trp = [set() for i in range(13)]
        self.fp = [set() for i in range(6)]

    def complete_schedule(self):
        pass
        
    def valid_schedule(self):
        pass
    
    def assign_game(self, game_id: str, day: int, slot: int):
        # Day = 0 refers to mwf, and day = 1 refers to tr
        if day == 0: self.mwfg[slot].add(game_id)
        elif day == 1: self.trg[slot].add(game_id)

    def assign_practice(self, practice: Practice):
        pass
