'''
This class uses objects of the class 'Slot' to build schedules that can be processed by the constraint handling classes
and placed into the tree structure generated by the Tree class. Every object in the schedule must be of the class 'Slot'.

'''

from ScheduleObjects.Slot import Slot
from ScheduleObjects.Game import Game
from ScheduleObjects.Practice import Practice

class Schedule:

    # Empty constructor (TODO)
    def __init__(self, mwf_g: "list[Slot]", tr_g: "list[Slot]", mw_p: "list[Slot]", tr_p: "list[Slot]", f_p: "list[Slot]") -> None:
        self.mwf_g = mwf_g
        self.tr_g = tr_g
        self.mw_p = mw_p
        self.tr_p = tr_p
        self.f_p = f_p

    def complete_schedule():
        pass
        
    def valid_schedule():
        pass
    
    def assign_game(game: Game):
        pass

    def assign_practice(practice: Practice):
        pass